name: Kubernetes API Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up kubeconfig
        run: |
          mkdir -p "${HOME}/.kube"
          echo "${{ secrets.KUBE_CONFIG }}" > "${HOME}/.kube/config"
          chmod 600 "${HOME}/.kube/config"
          echo "KUBECONFIG=${HOME}/.kube/config" >> $GITHUB_ENV

      - name: Install kubectl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl jq

      - name: Get Kubernetes Pods
        id: get_pods
        run: |
          echo "Fetching all pods..."
          POD_NAMES=$(kubectl get pods -A -o json | jq -r '.items[].metadata.name' | paste -sd "," -)
          echo "pods=$POD_NAMES"

      - name: Locate TXT files
        id: locate_txt    
        run: |
          echo "Locating all .txt files..."
          TXT_FILES=$(find . -name '*.txt' | paste -sd "," -)
          TXT_FILES=$(find $GITHUB_WORKSPACE -name '*.txt' | paste -sd "," -)
          if [ -z "$TXT_FILES" ]; then
            echo "No .txt files found."
            TXT_FILES="none"
          else
            echo "Found .txt files: $TXT_FILES"
          fi  
          echo "txt_files=$TXT_FILES"

