# name: Kubernetes API Workflow

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure Kubernetes
#         uses: azure/k8s-set-context@v3
#         with:
#           kubeconfig: ${{ secrets.KUBE_CONFIG }}

#       - name: Set up Kubectl
#         run: |
#             mkdir ${HOME}/.kube
#             echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config

#       - name: Get Kubernetes Secret
#         id: get_pods
#         run: |
#           kubectl get pods -A
#           echo "::set-output name=pods::$(kubectl get pods -A -o json | jq -r '.items[] | .metadata.name')"

#       - name: Locate JSON files
#         id: locate_json
#         run: |
#           TXT_FILES=$(find ./github-actions -name '*.txt')
#           echo "::set-output name=txt_files::$TXT_FILES"